import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUIDv7 primary key generated by Postgres 18, so ids sort by creation time. */
export const primaryId = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

export const timestampTz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const createdAt = () => timestampTz('created_at').notNull().defaultNow();
export const updatedAt = () => timestampTz('updated_at').notNull().defaultNow();
