import {
  bullets,
  callout,
  decision,
  doc,
  field,
  h,
  numbered,
  p,
  rule,
  table,
  tasks,
  toc,
} from './builders.ts';

/** RFC: propose a change, weigh the options, record who decides. */
export const RFC = doc(
  field('Status', 'Draft'),
  field('Authors'),
  field('Deciders'),
  field('Decision date'),
  rule(),
  toc(),
  callout('info', p('TL;DR: one paragraph a busy reader can stop after: what changes, and why now.')),
  h(2, 'Context'),
  p('What is true today, what hurts, and what we measured. Link the issues and pages it rests on.'),
  h(2, 'Goals'),
  bullets('What this must achieve', 'How we will know it worked'),
  h(2, 'Non-goals'),
  bullets('What this deliberately leaves out'),
  h(2, 'Proposal'),
  p('The design in enough detail that someone else could build it.'),
  h(3, 'Rollout'),
  numbered('Behind a flag', 'Dual-write and backfill', 'Cut reads over', 'Remove the old path'),
  h(2, 'Alternatives considered'),
  table(
    ['Option', 'For', 'Against'],
    ['Option A', '', ''],
    ['Option B', '', ''],
    ['Do nothing', 'No work now', 'The cost of today, kept'],
  ),
  h(2, 'Risks and open questions'),
  bullets('What could go wrong, and how we would notice'),
  h(2, 'Decision'),
  decision(p('Filled in by the deciders: accepted, rejected or deferred, and why.')),
);

/** Postmortem: blameless account of an incident and what changes because of it. */
export const POSTMORTEM = doc(
  field('Severity', 'SEV-2'),
  field('Incident commander'),
  field('Date'),
  field('Duration'),
  rule(),
  callout('note', p('This review is blameless. We look for system fixes, not fault.')),
  toc(),
  h(2, 'Summary'),
  p('What happened, who was affected and for how long, in two or three sentences.'),
  h(2, 'Impact'),
  table(
    ['Area', 'Impact'],
    ['Customers or teams affected', ''],
    ['Requests, revenue or data affected', ''],
    ['SLO budget used', ''],
  ),
  h(2, 'Timeline'),
  p('All times in UTC. Start at the first signal, end when the impact was over.'),
  table(
    ['Time (UTC)', 'Event'],
    ['00:00', 'First alert fires'],
    ['00:05', 'Incident declared'],
    ['00:40', 'Mitigated'],
    ['01:10', 'Resolved'],
  ),
  h(2, 'Root cause'),
  p('The conditions that made this possible, not the person who triggered it.'),
  h(2, 'What went well'),
  bullets(''),
  h(2, 'What went poorly'),
  bullets(''),
  h(2, 'Action items'),
  tasks(
    'Fix the immediate cause',
    'Add the alert that would have caught it sooner',
    'Update the runbook',
  ),
);

/** Runbook: what an on-call engineer does, step by step, at 3 a.m. */
export const RUNBOOK = doc(
  field('Service'),
  field('Owner team'),
  field('Last verified'),
  rule(),
  callout(
    'warning',
    p('If customers are affected, declare an incident before you start debugging.'),
  ),
  h(2, 'When to use this'),
  p('The alert or symptom that sends someone here, quoted exactly as it appears.'),
  h(2, 'Before you start'),
  tasks('Acknowledge the page', 'Open the service dashboard', 'Post in the incident channel'),
  h(2, 'Diagnose'),
  numbered('Check the error rate and latency', 'Check recent deploys', 'Check dependencies'),
  h(2, 'Mitigate'),
  numbered('Roll back the last deploy if it lines up', 'Scale out if saturated', 'Fail over'),
  h(2, 'Verify'),
  p('What healthy looks like, and how long to watch before standing down.'),
  h(2, 'Escalate'),
  table(
    ['Who', 'How to reach them', 'When'],
    ['Owning team on-call', 'Page through the on-call rota', 'Not mitigated in 30 minutes'],
    ['Platform on-call', '', 'A dependency is down'],
  ),
);
