import {
  Activity,
  AlarmClock,
  Archive,
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  AtSign,
  Bell,
  Bold,
  Bookmark,
  Box,
  Bug,
  Building2,
  Calendar,
  ChevronLeft,
  CircleDot,
  CircleUserRound,
  Clock,
  Command,
  Copy,
  CornerDownRight,
  Database,
  Eye,
  FilePlus,
  Flag,
  Flame,
  Globe,
  Heart,
  Hexagon,
  House,
  Image,
  Info,
  Italic,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Minus,
  Moon,
  Option,
  Palette,
  PanelLeft,
  Paperclip,
  Printer,
  Puzzle,
  RefreshCw,
  Rocket,
  Shapes,
  Shield,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Sun,
  Tag,
  Target,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  WifiOff,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The design review's icon set (docs/design/premium/kit.js, `P`) under its names where they
 * read well, as Lucide icons. The last group is the palette a custom issue type picks from.
 */
export const KIT_ICONS = {
  home: House,
  me: CircleUserRound,
  user: User,
  list: List,
  sliders: SlidersHorizontal,
  link: Link,
  clip: Paperclip,
  eye: Eye,
  bell: Bell,
  moon: Moon,
  sun: Sun,
  layers: Layers,
  spark: Sparkles,
  shield: Shield,
  palette: Palette,
  mail: Mail,
  database: Database,
  refresh: RefreshCw,
  pulse: Activity,
  message: MessageSquare,
  clock: Clock,
  tag: Tag,
  calendar: Calendar,
  target: Target,
  sidebar: PanelLeft,
  lock: Lock,
  building: Building2,
  zap: Zap,
  bookmark: Bookmark,
  subtask: CornerDownRight,
  copy: Copy,
  smile: Smile,
  bold: Bold,
  italic: Italic,
  checklist: ListChecks,
  image: Image,
  at: AtSign,
  archive: Archive,
  snooze: AlarmClock,
  bug: Bug,
  undo: Undo2,
  upload: Upload,
  print: Printer,
  'file-plus': FilePlus,
  offline: WifiOff,
  warning: TriangleAlert,
  info: Info,
  minus: Minus,
  back: ChevronLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  /** Kbd: the Apple command, option and shift keys. */
  command: Command,
  option: Option,
  shift: ArrowBigUp,
  // Custom issue types pick from these as well as the names above.
  flag: Flag,
  dot: CircleDot,
  hexagon: Hexagon,
  rocket: Rocket,
  idea: Lightbulb,
  wrench: Wrench,
  megaphone: Megaphone,
  shapes: Shapes,
  box: Box,
  grid: LayoutGrid,
  globe: Globe,
  heart: Heart,
  flame: Flame,
  puzzle: Puzzle,
} satisfies Record<string, LucideIcon>;

export type KitIconName = keyof typeof KIT_ICONS;
