import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Primary key every table uses: UUIDv7 generated by Postgres 18, so inserts are
 * B-tree sequential and ordering by id is chronological.
 */
export function primaryId() {
  return uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);
}

/** A UUID column referencing another table's primary key. */
export function uuidRef(name: string) {
  return uuid(name);
}

/** Timestamps with time zone; every timestamp in the schema uses this. */
export function timestamptz(name: string) {
  return timestamp(name, { withTimezone: true, mode: 'date' });
}

/**
 * `created_at` and `updated_at`, both required. Services set `updated_at` on
 * every write; there is no trigger, so the column is honest about who wrote it.
 */
export function timestamps() {
  return {
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    updatedAt: timestamptz('updated_at').notNull().defaultNow(),
  };
}
