import { z } from 'zod';

const flag = z.stringbool().default(false);

export const updaterEnvSchema = z.object({
  /** Shared with the app; generated by the installer. */
  UPDATER_TOKEN: z.string().min(32),
  UPDATER_PORT: z.coerce.number().int().min(1).max(65_535).default(8090),
  /** The install folder, mounted at the same path: compose file, .env, data, backups. */
  BEMMOLY_DIR: z.string().min(1).default('/var/bemmoly'),
  COMPOSE_PROJECT: z.string().min(1).default('bemmoly'),
  APP_SERVICE: z.string().min(1).default('bemmoly'),
  /** The only repository updates come from; the API takes a version, never an image. */
  BEMMOLY_IMAGE: z.string().min(1).default('ghcr.io/bemmoly/bemmoly'),
  /** Off by default: an image whose signature cannot be verified is refused. */
  BEMMOLY_ALLOW_UNSIGNED_UPDATES: flag,
  /** Air-gapped installs and tests: use images already loaded, never pull. */
  BEMMOLY_UPDATER_LOCAL_IMAGES: flag,
  COSIGN_PUBLIC_KEY: z.string().min(1).optional(),
  COSIGN_IDENTITY_REGEXP: z.string().default('^https://github\\.com/bemmoly/bemmoly/'),
  COSIGN_OIDC_ISSUER: z.url().default('https://token.actions.githubusercontent.com'),
  COSIGN_BINARY: z.string().default('/usr/local/bin/cosign'),
  READY_TIMEOUT_MS: z.coerce.number().int().min(10_000).default(180_000),
  RETENTION_DAYS: z.coerce.number().int().min(1).max(90).default(7),
  LOG_LEVEL: z.enum(['error', 'warn', 'info', 'debug']).default('info'),
});

export type UpdaterEnv = z.output<typeof updaterEnvSchema>;

/** The only place the updater reads the environment. Exits on a bad key. */
export function loadUpdaterEnv(): UpdaterEnv {
  const result = updaterEnvSchema.safeParse(
    Object.fromEntries(Object.entries(process.env).filter(([, value]) => Boolean(value))),
  );
  if (result.success) return result.data;
  const problems = result.error.issues.map(
    (issue) => `  - ${issue.path.join('.')}: ${issue.message}`,
  );
  process.stderr.write(`Invalid updater environment:\n${problems.join('\n')}\n`);
  process.exit(1);
}
